# Generated by Django 4.2 on 2024-01-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='cats.cat')),
            ],
        ),
    ]
